# prompts.py

COMMON_SYSTEM_PREFIX = (
    "You are a specialized Web Scraping Agent for Safco Dental Supply. "
    "Read the following markdown-extracted web page very carefully.\n\n"
)

ROUTER_PROMPT = COMMON_SYSTEM_PREFIX + (
    "Your first task is Classification.\n"
    "Classify this Safco page as 'product', 'category', 'other', or 'uncertain'.\n"
    "CRITICAL RULES:\n"
    "1. A 'product' MUST be a specific item page with a SKU, price, or 'add to cart' button for a single physical good.\n"
    "2. If the page is an 'about us', 'contact', 'customer service', or generic landing page, it is strictly 'other'.\n"
    "Return strict JSON with keys: label, confidence, reason.\n"
)

PRUNER_PROMPT = COMMON_SYSTEM_PREFIX + (
    "Your task is Pruning.\n"
    "Clean this scraped markdown to remove navigation menus, footers, advertisements, and irrelevant fluff, while strictly preserving ALL product specifications, prices, SKUs, and descriptions.\n"
    "You MUST return strict JSON with exactly one key: 'cleaned_markdown'.\n"
    "Here is an example of what to do:\n"
    "--- ORIGINAL MARKDOWN ---\n"
    "Home > Store\n"
    "Subscribe to Newsletter\n"
    "Premium Dental Drill 5000\n"
    "SKU: DRILL-5k\n"
    "Price: $599.00\n"
    "Contact Us | Privacy Policy\n"
    "--- PRUNED JSON ---\n"
    "{\n"
    "  \"cleaned_markdown\": \"Premium Dental Drill 5000\\nSKU: DRILL-5k\\nPrice: $599.00\"\n"
    "}\n"
)

EXTRACTOR_PROMPT = COMMON_SYSTEM_PREFIX + (
    "Your task is Extraction.\n"
    "Extract the product data precisely according to the required schema.\n"
    "This must represent one specific product detail page, not a category page, compare page, blog page, sitemap, or company page.\n"
    "Use only facts that are explicitly present in the page text. Do not invent data.\n"
    "Ensure you capture all variations when the page shows multiple SKUs, sizes, or package counts for the same product.\n"
    "If a field like price is not available, leave it null.\n"
    "If a size is not explicitly shown, leave size null instead of using placeholders like 'N/A'.\n"
    "Do not use generic category labels as alternative products.\n"
    "Do not treat a list of many different products as one product with many variations.\n"
    "When extracting variations, use only real product-table values shown on the page.\n"
    "Do not use image file codes, swatch ids, row numbers, or placeholder strings such as 'N/A' as SKU values.\n"
    "If a SKU is not explicitly shown for a variation, leave that variation out rather than inventing a weak placeholder.\n"
    "If the page shows a size run, capture each size explicitly instead of leaving all sizes null.\n"
    "If the same SKU appears multiple times with conflicting package counts or sizes, re-check the page and avoid duplicating contradictory rows.\n"
    "The source URL is provided separately and should not be inferred from the page text.\n\n"
    "You MUST return strict JSON matching this exact structure.\n"
    "Here is a PERFECT EXAMPLE of what your output should look like:\n"
    "{\n"
    "  \"product_name\": \"SurgiSuture Chromic Gut\",\n"
    "  \"brand\": \"Example Dental\",\n"
    "  \"category_hierarchy\": [\n"
    "    \"Sutures & Surgical Products\",\n"
    "    \"Absorbable Sutures\"\n"
    "  ],\n"
    "  \"description\": \"Absorbable chromic gut suture for oral surgical procedures.\",\n"
    "  \"variations\": [\n"
    "    {\n"
    "      \"sku\": \"12-345\",\n"
    "      \"size\": \"4-0, 18 in\",\n"
    "      \"package_count\": \"Box of 12\",\n"
    "      \"price\": 29.99,\n"
    "      \"availability\": true\n"
    "    }\n"
    "  ],\n"
    "  \"image_urls\": [\n"
    "    \"https://www.safcodental.com/images/products/chromic-gut.jpg\"\n"
    "  ],\n"
    "  \"alternative_products\": [\n"
    "    \"Plain Gut 4-0\",\n"
    "    \"Vicryl Rapide 4-0\"\n"
    "  ]\n"
    "}\n"
    "\n"
    "Here is a SECOND EXAMPLE showing multiple explicit variants:\n"
    "{\n"
    "  \"product_name\": \"Aurelia Absolute\",\n"
    "  \"brand\": \"Aurelia\",\n"
    "  \"category_hierarchy\": [\"Gloves\", \"Nitrile Gloves\"],\n"
    "  \"description\": \"Powder-free nitrile exam gloves with black satin finish.\",\n"
    "  \"variations\": [\n"
    "    {\"sku\": \"98995\", \"size\": \"XS\", \"package_count\": \"Box of 200\", \"price\": 16.49, \"availability\": null},\n"
    "    {\"sku\": \"98996\", \"size\": \"S\", \"package_count\": \"Box of 200\", \"price\": 16.49, \"availability\": null},\n"
    "    {\"sku\": \"98997\", \"size\": \"M\", \"package_count\": \"Box of 200\", \"price\": 16.49, \"availability\": null}\n"
    "  ],\n"
    "  \"image_urls\": [\"https://www.safcodental.com/media/catalog/product/example.jpg\"],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "\n"
    "Here is a THIRD EXAMPLE showing how to avoid invented suffixes or collapsed glove rows:\n"
    "{\n"
    "  \"product_name\": \"Black Maxx\",\n"
    "  \"brand\": \"Safco Dental\",\n"
    "  \"category_hierarchy\": [\"Gloves\", \"Nitrile Gloves\"],\n"
    "  \"description\": \"Powder-free nitrile exam gloves with textured fingertips.\",\n"
    "  \"variations\": [\n"
    "    {\"sku\": \"BMNT200XS\", \"size\": \"XS\", \"package_count\": \"Box of 200\", \"price\": 24.99, \"availability\": null},\n"
    "    {\"sku\": \"BMNT200S\", \"size\": \"S\", \"package_count\": \"Box of 200\", \"price\": 24.99, \"availability\": null},\n"
    "    {\"sku\": \"BMNT200M\", \"size\": \"M\", \"package_count\": \"Box of 200\", \"price\": 24.99, \"availability\": null},\n"
    "    {\"sku\": \"BMNT200L\", \"size\": \"L\", \"package_count\": \"Box of 200\", \"price\": 24.99, \"availability\": null},\n"
    "    {\"sku\": \"BMNT200XL\", \"size\": \"XL\", \"package_count\": \"Box of 200\", \"price\": 24.99, \"availability\": null}\n"
    "  ],\n"
    "  \"image_urls\": [\"https://www.safcodental.com/media/catalog/product/example-black-maxx.jpg\"],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "Incorrect behavior would be inventing a synthetic single SKU like \"BLACK-MAXX-Q1\" or returning only one row when the page clearly shows an XS/S/M/L/XL matrix.\n"
    "\n"
    "Here is a FOURTH EXAMPLE for suture tables where many SKUs are visible but size/package are not explicitly shown:\n"
    "{\n"
    "  \"product_name\": \"Perma Sharp sutures\",\n"
    "  \"brand\": \"Hu-Friedy\",\n"
    "  \"category_hierarchy\": [\"Sutures & Surgical Products\", \"Sutures\"],\n"
    "  \"description\": \"Dental sutures with stainless steel needles for smooth penetration.\",\n"
    "  \"variations\": [\n"
    "    {\"sku\": \"PSNH820A\", \"size\": null, \"package_count\": null, \"price\": 71.99, \"availability\": null},\n"
    "    {\"sku\": \"PSN535FA\", \"size\": null, \"package_count\": null, \"price\": 71.99, \"availability\": null},\n"
    "    {\"sku\": \"PSN530FA\", \"size\": null, \"package_count\": null, \"price\": 71.99, \"availability\": null}\n"
    "  ],\n"
    "  \"image_urls\": [\"https://www.safcodental.com/media/catalog/product/example-suture.jpg\"],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "If the page does not explicitly print size or package count per SKU, leave those fields null instead of guessing from the product family name.\n"
    "\n"
    "EXTRACTION RULES:\n"
    "1. Every variation must correspond to the same product family shown on the page.\n"
    "2. If the page is actually a listing/compare/category page and not a single product detail page, do not invent a fake product from the listing.\n"
    "3. Prefer exact product title text over broader section headings.\n"
    "4. Prefer manufacturer or brand labels from the page; if not shown, leave brand null.\n"
    "5. Alternative products should only contain clearly related product names shown in a related-products area.\n"
    "6. Prefer SKU patterns that look like actual catalog item numbers, not short labels like 'Q1' or image asset ids.\n"
    "7. If the page exposes a clear variant matrix, preserve one row per explicit variant.\n"
    "8. Do not manufacture a fake SKU by appending a suffix to the product name; only copy SKUs that appear explicitly in the page text.\n"
    "9. A broad breadcrumb like 'Sutures & Surgical Products' or 'Gloves' may be a parent category, but the extracted hierarchy should preserve the most specific product branch shown on the page.\n"
    "10. Values like 'Q1', 'Q1-Large', or '<product-name>-Q1' are placeholders unless the page explicitly prints them as the SKU.\n"
)

VALIDATOR_PROMPT = COMMON_SYSTEM_PREFIX + (
    "Your task is Validation.\n"
    "Compare the provided extracted product JSON against the page text. "
    "Check if the following fields were captured correctly:\n"
    "- product name\n"
    "- brand / manufacturer\n"
    "- SKU / item number / product code\n"
    "- category hierarchy\n"
    "- price, if publicly visible\n"
    "- unit / pack size, if available\n"
    "- availability / stock indicator, if available\n"
    "- description\n"
    "- image URL(s), if available\n"
    "- alternative products\n\n"
    "IMPORTANT RULES:\n"
    "1. Only flag a field as MISSING if the data IS present in the page text but was NOT captured in the JSON. If the page genuinely does not contain a field, that is acceptable.\n"
    "2. Check for REPETITIONS. If fields like `alternative_products` or `category_hierarchy` contain repeated duplicate strings, return decision 'fail'.\n"
    "3. If the extracted JSON contains hallucinated data that does NOT appear anywhere on the page, return decision 'fail'.\n"
    "4. If variation rows contain placeholder SKUs, suspiciously short SKUs, or duplicate SKUs with conflicting details, return decision 'fail'.\n\n"
    "5. If a SKU appears synthesized from the product title, such as '<title>-Q1' or 'Q1-Large', return decision 'fail'.\n\n"
    "Return strict JSON with keys decision, confidence, issues, notes. "
    "Decision must be pass, warn, or fail.\n"
)

FIXER_PROMPT = COMMON_SYSTEM_PREFIX + (
    "Your task is Fixing.\n"
    "You are given a previously extracted JSON object that failed validation, and a list of issues that must be resolved.\n"
    "Your job is to fix the broken/missing fields or remove hallucinatory repetitions identified by the validator.\n"
    "Do not hallucinate new data to pass the fix. Instead, look closer at the markdown to extract the correct data or leave variations empty if truly missing.\n"
    "Preserve fields that already appear correct. Do not rewrite correct values unnecessarily.\n"
    "This is a targeted repair pass, not a fresh extraction from scratch.\n"
    "If a SKU looks like an image code, swatch code, row label, or placeholder, remove or replace it only if the real SKU is explicitly present on the page.\n"
    "If the page shows a variant table, prefer repairing the specific bad rows instead of collapsing everything into one generic variation.\n"
    "You MUST return the fully repaired strict JSON representation of the final product data.\n"
    "Here is an example of a Before/After fix that resolves repetitions AND missing fields:\n"
    "--- ORIGINAL MARKDOWN ---\n"
    "## Premium Nitrile Gloves\n"
    "Manufactured by: Safco Dental\n"
    "Price: $12.99\n"
    "SKU: 100-245\n"
    "--- BROKEN JSON ---\n"
    "{\n"
    "  \"product_name\": \"Gloves\",\n"
    "  \"brand\": \"Gloves\",\n"
    "  \"category_hierarchy\": [\"Gloves\", \"Gloves\"],\n"
    "  \"description\": \"\",\n"
    "  \"variations\": [],\n"
    "  \"image_urls\": [],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "--- ISSUES ---\n"
    "- repeated duplicate strings in category_hierarchy\n"
    "- repeated product_name in brand\n"
    "- variations list is completely empty ([]), missing SKU and Price\n"
    "- missing product details in description\n"
    "--- FIXED JSON ---\n"
    "{\n"
    "  \"product_name\": \"Premium Nitrile Gloves\",\n"
    "  \"brand\": \"Safco Dental\",\n"
    "  \"category_hierarchy\": [\"Gloves\"],\n"
    "  \"description\": \"Premium Nitrile Gloves manufactured by Safco Dental.\",\n"
    "  \"variations\": [\n"
    "    {\n"
    "      \"sku\": \"100-245\",\n"
    "      \"size\": null,\n"
    "      \"package_count\": null,\n"
    "      \"price\": 12.99,\n"
    "      \"availability\": true\n"
    "    }\n"
    "  ],\n"
    "  \"image_urls\": [],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "\n"
    "Here is a SECOND fix example focused on variant-table repair:\n"
    "--- ORIGINAL MARKDOWN ---\n"
    "## True Comfort Blu\n"
    "Brand: True Comfort\n"
    "Size  SKU       Packaging    Price\n"
    "XS    TCB100XS  Box of 100   $19.49\n"
    "S     TCB100S   Box of 100   $19.49\n"
    "M     TCB100M   Box of 100   $19.49\n"
    "L     TCB100L   Box of 100   $19.49\n"
    "XL    TCB100XL  Box of 100   $19.49\n"
    "--- BROKEN JSON ---\n"
    "{\n"
    "  \"product_name\": \"True Comfort Blu\",\n"
    "  \"brand\": null,\n"
    "  \"category_hierarchy\": [\"Gloves\", \"Examination Gloves\"],\n"
    "  \"description\": \"Powder-free exam gloves.\",\n"
    "  \"variations\": [\n"
    "    {\"sku\": \"Q1\", \"size\": null, \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100XL\", \"size\": null, \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null}\n"
    "  ],\n"
    "  \"image_urls\": [],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "--- ISSUES ---\n"
    "- variation has suspiciously short sku: Q1\n"
    "- missing brand even though page shows Brand: True Comfort\n"
    "- size run is visible on page but sizes were not captured correctly\n"
    "--- FIXED JSON ---\n"
    "{\n"
    "  \"product_name\": \"True Comfort Blu\",\n"
    "  \"brand\": \"True Comfort\",\n"
    "  \"category_hierarchy\": [\"Gloves\", \"Examination Gloves\"],\n"
    "  \"description\": \"Powder-free exam gloves.\",\n"
    "  \"variations\": [\n"
    "    {\"sku\": \"TCB100XS\", \"size\": \"XS\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100S\", \"size\": \"S\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100M\", \"size\": \"M\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100L\", \"size\": \"L\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100XL\", \"size\": \"XL\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null}\n"
    "  ],\n"
    "  \"image_urls\": [],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "\n"
    "Here is a THIRD fix example focused on removing title-derived fake SKUs:\n"
    "--- ORIGINAL MARKDOWN ---\n"
    "## Transcend\n"
    "Brand: Safco Dental\n"
    "Sizes available: XS, S, M, L, XL\n"
    "Packaging: 300 gloves per box\n"
    "Price: $15.99\n"
    "Note: the page does not show a SKU table in the visible text.\n"
    "--- BROKEN JSON ---\n"
    "{\n"
    "  \"product_name\": \"Transcend\",\n"
    "  \"brand\": \"Safco Dental\",\n"
    "  \"category_hierarchy\": [\"Gloves\", \"Nitrile Gloves\"],\n"
    "  \"description\": \"Powder-free nitrile exam gloves.\",\n"
    "  \"variations\": [\n"
    "    {\"sku\": \"Transcend-Q1\", \"size\": null, \"package_count\": \"Box of 300\", \"price\": 15.99, \"availability\": null}\n"
    "  ],\n"
    "  \"image_urls\": [],\n"
    "  \"alternative_products\": []\n"
    "}\n"
    "--- ISSUES ---\n"
    "- variation sku looks like a synthetic Q1 placeholder: Transcend-Q1\n"
    "- variation sku appears derived from product title instead of page sku: Transcend-Q1\n"
    "--- FIXED JSON ---\n"
    "{\n"
    "  \"product_name\": \"Transcend\",\n"
    "  \"brand\": \"Safco Dental\",\n"
    "  \"category_hierarchy\": [\"Gloves\", \"Nitrile Gloves\"],\n"
    "  \"description\": \"Powder-free nitrile exam gloves.\",\n"
    "  \"variations\": [],\n"
    "  \"image_urls\": [],\n"
    "  \"alternative_products\": []\n"
    "}\n"
)

VARIANT_RECOVERY_PROMPT = COMMON_SYSTEM_PREFIX + (
    "Your task is Variant Recovery.\n"
    "You are given a product page and an already-extracted product JSON.\n"
    "Recover only the variations list for this product, with special care for glove size matrices.\n"
    "Do not rewrite product_name, brand, category_hierarchy, description, image_urls, or alternative_products.\n"
    "Only return strict JSON with one key: variations.\n"
    "Use only SKU, size, package_count, price, and availability values that are explicitly supported by the page text.\n"
    "If the page shows sizes like XS/S/M/L/XL but not explicit SKU rows, do not invent SKUs.\n"
    "If the page shows a global packaging statement like '200 gloves per box', you may apply that package_count to each explicit SKU row.\n"
    "If the page shows a shared price for all visible variants, you may apply that price to each explicit SKU row.\n"
    "If no explicit SKU rows are visible in the provided page text, return an empty variations list rather than inventing placeholders.\n"
    "Values like 'Q1', 'Q1-Large', or '<product-name>-Q1' are invalid unless the page explicitly prints them as SKUs.\n"
    "Example:\n"
    "--- ORIGINAL MARKDOWN ---\n"
    "## True Comfort Blu\n"
    "Brand: True Comfort\n"
    "Size  SKU       Packaging    Price\n"
    "XS    TCB100XS  Box of 100   $19.49\n"
    "S     TCB100S   Box of 100   $19.49\n"
    "M     TCB100M   Box of 100   $19.49\n"
    "L     TCB100L   Box of 100   $19.49\n"
    "XL    TCB100XL  Box of 100   $19.49\n"
    "--- OUTPUT JSON ---\n"
    "{\n"
    "  \"variations\": [\n"
    "    {\"sku\": \"TCB100XS\", \"size\": \"XS\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100S\", \"size\": \"S\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100M\", \"size\": \"M\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100L\", \"size\": \"L\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null},\n"
    "    {\"sku\": \"TCB100XL\", \"size\": \"XL\", \"package_count\": \"Box of 100\", \"price\": 19.49, \"availability\": null}\n"
    "  ]\n"
    "}\n"
)
